version: "3"

services:
  front:
    container_name: front
    build: ./front
    restart: unless-stopped
    working_dir: "/front"
    volumes:
      - "../front/:/front"
    ports:
      - "1000:1000"

  back:
    container_name: back
    build: ./back
    restart: unless-stopped
    ports:
      - "2000:2000"
    working_dir: "/back"
    volumes:
      - ../back:/back
    # depends_on:
    #   - postgres

  # postgres:
  #   container_name: postgres
  #   image: postgres:alpine
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data/
  #   environment:
  #     - "POSTGRES_USER=user"
  #     - "POSTGRES_PASSWORD=pass"
  #     - "POSTGRES_DB=db"
  #     - "POSTGRES_HOST_AUTH_METHO=trust"
  #   expose:
  #     - 5432
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U user -d db"]
  #     interval: 1s
  #     timeout: 1s
  #     retries: 10

# volumes:
#   postgres_data:
